/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialServicesRouteImport } from './routes/special-services'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as DriverPortalCopyRouteImport } from './routes/driver-portal - Copy'
import { Route as DriverPortalRouteImport } from './routes/driver-portal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookCopyRouteImport } from './routes/book - Copy'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'

const SpecialServicesRoute = SpecialServicesRouteImport.update({
  id: '/special-services',
  path: '/special-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalCopyRoute = DriverPortalCopyRouteImport.update({
  id: '/driver-portal - Copy',
  path: '/driver-portal - Copy',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPortalRoute = DriverPortalRouteImport.update({
  id: '/driver-portal',
  path: '/driver-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCopyRoute = BookCopyRouteImport.update({
  id: '/book - Copy',
  path: '/book - Copy',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/book - Copy': typeof BookCopyRoute
  '/contact': typeof ContactRoute
  '/driver-portal': typeof DriverPortalRoute
  '/driver-portal - Copy': typeof DriverPortalCopyRoute
  '/our-story': typeof OurStoryRoute
  '/services': typeof ServicesRoute
  '/special-services': typeof SpecialServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/book - Copy': typeof BookCopyRoute
  '/contact': typeof ContactRoute
  '/driver-portal': typeof DriverPortalRoute
  '/driver-portal - Copy': typeof DriverPortalCopyRoute
  '/our-story': typeof OurStoryRoute
  '/services': typeof ServicesRoute
  '/special-services': typeof SpecialServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/book - Copy': typeof BookCopyRoute
  '/contact': typeof ContactRoute
  '/driver-portal': typeof DriverPortalRoute
  '/driver-portal - Copy': typeof DriverPortalCopyRoute
  '/our-story': typeof OurStoryRoute
  '/services': typeof ServicesRoute
  '/special-services': typeof SpecialServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/book - Copy'
    | '/contact'
    | '/driver-portal'
    | '/driver-portal - Copy'
    | '/our-story'
    | '/services'
    | '/special-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/book - Copy'
    | '/contact'
    | '/driver-portal'
    | '/driver-portal - Copy'
    | '/our-story'
    | '/services'
    | '/special-services'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/book - Copy'
    | '/contact'
    | '/driver-portal'
    | '/driver-portal - Copy'
    | '/our-story'
    | '/services'
    | '/special-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  BookCopyRoute: typeof BookCopyRoute
  ContactRoute: typeof ContactRoute
  DriverPortalRoute: typeof DriverPortalRoute
  DriverPortalCopyRoute: typeof DriverPortalCopyRoute
  OurStoryRoute: typeof OurStoryRoute
  ServicesRoute: typeof ServicesRoute
  SpecialServicesRoute: typeof SpecialServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/special-services': {
      id: '/special-services'
      path: '/special-services'
      fullPath: '/special-services'
      preLoaderRoute: typeof SpecialServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal - Copy': {
      id: '/driver-portal - Copy'
      path: '/driver-portal - Copy'
      fullPath: '/driver-portal - Copy'
      preLoaderRoute: typeof DriverPortalCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-portal': {
      id: '/driver-portal'
      path: '/driver-portal'
      fullPath: '/driver-portal'
      preLoaderRoute: typeof DriverPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book - Copy': {
      id: '/book - Copy'
      path: '/book - Copy'
      fullPath: '/book - Copy'
      preLoaderRoute: typeof BookCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  BookCopyRoute: BookCopyRoute,
  ContactRoute: ContactRoute,
  DriverPortalRoute: DriverPortalRoute,
  DriverPortalCopyRoute: DriverPortalCopyRoute,
  OurStoryRoute: OurStoryRoute,
  ServicesRoute: ServicesRoute,
  SpecialServicesRoute: SpecialServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
